#!/bin/bash -l 
#SBATCH -p RM
#SBATCH -N 2
#SBATCH -n 56
#SBATCH -t 00:20:00 
#SBATCH -J multi-HW3
#SBATCH -o multi-HW3.%j.out
#SBATCH -e multi-HW3.%j.err

# Specify path to your input file here
INPUT=test

cd ${PWD}
for P in 28 56; do
	upcrun -np $P -shared-heap=1G ./pgen ${INPUT}
done
